import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import{Trophy,Flame,Clock,BookOpen,LogOut,PlusCircle,Medal,Sun,Moon,X,LayoutDashboard,Users,ChevronRight,UserRound,Instagram,Github}from'lucide-react';import'./style.css';import StudyAnalytics from'./components/StudyAnalytics.jsx';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const SUBJECTS=['Biology','Physics','Chemistry','Psychology'];
function words(s){return s.trim()?s.trim().split(/\s+/).length:0}function pts(hours,streak){return Math.round(hours*100)+Math.min(streak*10,100)}
function App(){const[user,setUser]=useState(null),[profile,setProfile]=useState(null),[board,setBoard]=useState([]),[sessions,setSessions]=useState([]),[auth,setAuth]=useState({email:'',password:'',username:''}),[mode,setMode]=useState('login'),[form,setForm]=useState({subject:'Biology',hours:'',topic:'',report:''}),[msg,setMsg]=useState(''),[theme,setTheme]=useState(()=>localStorage.getItem('80hd-theme')||'light'),[viewing,setViewing]=useState(null),[publicSessions,setPublicSessions]=useState([]),[reportLoading,setReportLoading]=useState(false),[analytics,setAnalytics]=useState(null),[reactions,setReactions]=useState({}),[page,setPage]=useState('dashboard');
useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));const{data:{subscription}}=supabase.auth.onAuthStateChange((_,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{loadBoard();if(user)loadMe()},[user]);useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('80hd-theme',theme)},[theme]);
async function loadBoard(){let{data}=await supabase.from('leaderboard').select('*').order('total_points',{ascending:false});setBoard(data||[])}
async function loadMe(){let{data:p}=await supabase.from('profiles').select('*').eq('id',user.id).single();setProfile(p);let{data:s}=await supabase.from('study_sessions').select('*').eq('user_id',user.id).order('studied_on',{ascending:false});let rows=s||[];setSessions(rows);try{let res=await fetch('/api/analytics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessions:rows})});if(res.ok)setAnalytics(await res.json());else setAnalytics(null)}catch{setAnalytics(null)}}
async function openReports(r){setPage('logs');setViewing(r);setPublicSessions([]);setReactions({});setReportLoading(true);let{data,error}=await supabase.from('study_sessions').select('id,user_id,subject,hours,topic,report,points,studied_on').eq('user_id',r.id).order('studied_on',{ascending:false}).limit(20);if(error)setMsg(error.message);else{let rows=data||[];setPublicSessions(rows);if(rows.length){let ids=rows.map(x=>x.id);let{data:rx}=await supabase.from('session_reactions').select('session_id,user_id,reaction').in('session_id',ids);let grouped={};(rx||[]).forEach(x=>{if(!grouped[x.session_id])grouped[x.session_id]=[];grouped[x.session_id].push(x)});setReactions(grouped)}}setReportLoading(false)}
async function reactTo(sessionId,reaction){let current=(reactions[sessionId]||[]).find(x=>x.user_id===user.id);if(current?.reaction===reaction){await supabase.from('session_reactions').delete().eq('session_id',sessionId).eq('user_id',user.id)}else{await supabase.from('session_reactions').upsert({session_id:sessionId,user_id:user.id,reaction},{onConflict:'session_id,user_id'})}let{data}=await supabase.from('session_reactions').select('session_id,user_id,reaction').eq('session_id',sessionId);setReactions(x=>({...x,[sessionId]:data||[]}))}
function ThemeButton(){return <button className="theme-toggle" type="button" aria-label="Toggle light and dark mode" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}</button>}
async function signup(e){e.preventDefault();setMsg('');let{data,error}=await supabase.auth.signUp({email:auth.email,password:auth.password,options:{data:{username:auth.username}}});if(error)return setMsg(error.message);if(data.user&&!data.session)setMsg('Account created. Check your email to confirm, then log in.');}
async function login(e){e.preventDefault();setMsg('');let{error}=await supabase.auth.signInWithPassword({email:auth.email,password:auth.password});if(error)setMsg(error.message)}
async function submit(e){e.preventDefault();setMsg('');if(words(form.report)<100)return setMsg('Your study report needs at least 100 words.');let h=Number(form.hours);if(!h||h<=0||h>12)return setMsg('Enter study time between 0 and 12 hours.');let today=new Date().toISOString().slice(0,10);let streak=1;if(profile?.last_study_date){let a=new Date(profile.last_study_date+'T00:00:00'),b=new Date(today+'T00:00:00'),d=Math.round((b-a)/86400000);streak=d===1?(profile.current_streak||0)+1:d===0?(profile.current_streak||1):1}let points=pts(h,streak);let{error}=await supabase.from('study_sessions').insert({user_id:user.id,subject:form.subject,hours:h,topic:form.topic,report:form.report,points,studied_on:today});if(error)return setMsg(error.message);await supabase.from('profiles').update({current_streak:streak,last_study_date:today}).eq('id',user.id);setForm({subject:'Biology',hours:'',topic:'',report:''});setMsg(`Submitted! +${points} points (${Math.round(h*100)} study + ${Math.min(streak*10,100)} streak).`);await loadMe();await loadBoard()}
if(!user)return <main className="auth"><div className="auth-theme"><ThemeButton/></div><section className="brand"><div className="logo">80</div><h1>80HD</h1><p>Study. Submit. Climb the board.</p></section><form className="card authcard" onSubmit={mode==='login'?login:signup}><h2>{mode==='login'?'Welcome back':'Join the league'}</h2>{mode==='signup'&&<input required placeholder="Username" value={auth.username} onChange={e=>setAuth({...auth,username:e.target.value})}/>}<input required type="email" placeholder="Email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password" value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/><button>{mode==='login'?'Log in':'Create account'}</button>{msg&&<p className="message">{msg}</p>}<p className="switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?"No account? Sign up":"Already have an account? Log in"}</p></form></main>;
let totalH=sessions.reduce((a,s)=>a+Number(s.hours),0),totalP=sessions.reduce((a,s)=>a+s.points,0);
const dashboard=<>
<section className="hero"><div><small>YOUR DASHBOARD</small><h1>Put in the hours.<br/>Earn your rank.</h1><p>Every valid session earns 100 points per hour plus your daily streak bonus.</p></div><div className="stats"><div><Trophy/><strong>{totalP}</strong><span>points</span></div><div><Clock/><strong>{totalH.toFixed(1)}</strong><span>hours</span></div><div><Flame/><strong>{profile?.current_streak||0}</strong><span>day streak</span></div></div></section>
<div className="grid"><section className="card submit"><h2><PlusCircle/> Log study session</h2><form onSubmit={submit}><label>Subject<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}>{SUBJECTS.map(x=><option key={x}>{x}</option>)}</select></label><label>Hours studied<input required type="number" step="0.25" min="0.25" max="12" placeholder="e.g. 1.5" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/></label><label>What did you study?<input required maxLength="120" placeholder="e.g. Cell respiration and ATP" value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></label><label>Study report <span>{words(form.report)}/100+ words</span><textarea required placeholder="Explain what you learned, practiced, found difficult, and what you need to review..." value={form.report} onChange={e=>setForm({...form,report:e.target.value})}/></label><button>Submit session</button>{msg&&<p className="message">{msg}</p>}</form></section>
<section className="card leaderboard"><h2><Trophy/> Competition board</h2><p className="muted">Ranked by total points</p><div className="rows">{board.map((r,i)=><button type="button" className="rank" key={r.id} onClick={()=>openReports(r)}><span className={"place place-"+(i+1)}>{i===0?<Trophy size={21}/>:i<3?<Medal size={20}/>:i+1}</span><div><b>@{r.username}</b><small>{Number(r.total_hours||0).toFixed(1)}h studied · {r.current_streak||0} day streak</small></div><strong>{r.total_points||0} pts</strong></button>)}{!board.length&&<p className="empty">No competitors yet.</p>}</div></section></div>
<StudyAnalytics analytics={analytics}/>
<section className="card history"><h2><BookOpen/> Your recent sessions</h2>{sessions.length?<div className="table">{sessions.slice(0,8).map(s=><div className="session" key={s.id}><span className={'pill '+s.subject.toLowerCase()}>{s.subject}</span><div><b>{s.topic}</b><small>{s.studied_on} · {s.hours} hours</small></div><strong>+{s.points}</strong></div>)}</div>:<p className="empty">Your first study session will appear here.</p>}</section>
</>;

const logsPage=<section className="logs-page">
  <div className="logs-heading"><div><small>PUBLIC STUDY LOGS</small><h1>Study logs</h1><p>View submitted sessions and reactions.</p></div></div>
  <div className="logs-shell card">
    <aside className="people-panel">
      <div className="people-panel-head"><b>Students</b><span>{board.length}</span></div>
      <div className="people-list">{board.map((r,i)=><button type="button" key={r.id} className={'person-row '+(viewing?.id===r.id?'active':'')} onClick={()=>openReports(r)}><span className="person-rank">{i===0?<Trophy size={17}/>:i+1}</span><div><b>@{r.username}</b><small>{Number(r.total_hours||0).toFixed(1)}h · {r.total_points||0} pts</small></div><ChevronRight size={17}/></button>)}</div>
    </aside>
    <div className="log-reader">
      {!viewing?<div className="reader-empty"><Users size={28}/><h2>Select a student</h2><p>Choose someone to view their submitted study logs.</p></div>:
      <><div className="reader-head"><div><small>STUDY LOG</small><h2>@{viewing.username}</h2><p>{Number(viewing.total_hours||0).toFixed(1)} hours · {viewing.total_points||0} points</p></div></div>
      {reportLoading?<p className="empty reader-loading">Loading reports...</p>:publicSessions.length?<div className="public-reports page-reports">{publicSessions.map(s=><article className="public-report log-entry" key={s.id}><div className="report-meta"><span className={'pill '+s.subject.toLowerCase()}>{s.subject}</span><span>{s.studied_on} · {s.hours}h · +{s.points} pts</span></div><h3>{s.topic}</h3><p>{s.report}</p><div className="reaction-bar">{['Verified','Good work','Questionable'].map(label=>{let list=reactions[s.id]||[],count=list.filter(x=>x.reaction===label).length,active=list.some(x=>x.user_id===user.id&&x.reaction===label);return <button type="button" key={label} className={'reaction '+(active?'active':'')} onClick={()=>reactTo(s.id,label)}>{label}{count>0&&<span>{count}</span>}</button>})}</div></article>)}</div>:<p className="empty reader-loading">No study reports yet.</p>}</>}
    </div>
  </div>
</section>;

const profilePage=<section className="profile-page"><div className="profile-card"><div className="profile-avatar">AC</div><div className="profile-copy"><small>PROFILE</small><h1>Angela Cheng</h1><p>human</p></div><div className="profile-links"><a href="https://www.instagram.com/angela._.3z3/" target="_blank" rel="noreferrer"><Instagram size={21}/><span>Instagram</span></a><a href="https://github.com/SyntaxError333" target="_blank" rel="noreferrer"><Github size={21}/><span>GitHub</span></a><a href="https://www.linkedin.com/in/angela-cheng-277b8843a/" target="_blank" rel="noreferrer"><span className="linkedin-mark" aria-hidden="true">in</span><span>LinkedIn</span></a></div></div></section>;

return <div className="site-shell">
<header><div><b>80HD</b><span>Academic Competition</span></div><div className="user">@{profile?.username}<ThemeButton/><button className="logout-button" type="button" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/><span>Log out</span></button></div></header>
<div className="app-body">
  <nav className="site-nav">
    <button className={page==='dashboard'?'active':''} onClick={()=>setPage('dashboard')}><LayoutDashboard size={18}/><span>Dashboard</span></button>
    <button className={page==='logs'?'active':''} onClick={()=>setPage('logs')}><Users size={18}/><span>Study logs</span></button>
    <button className={page==='profile'?'active':''} onClick={()=>setPage('profile')}><UserRound size={18}/><span>Profile</span></button>
  </nav>
  <main className="wrap page-stage" key={page}>{page==='dashboard'?dashboard:page==='logs'?logsPage:profilePage}
    <section className="rules"><b>SCORING</b><span>100 pts / hour</span><span>+</span><span>10 pts × streak day</span><span>•</span><span>Streak bonus capped at 100 pts/day</span></section>
    <footer className="angela-credit"><strong>80HD</strong><span>Created by Angela • Designed by Angela • Developed by Angela • Directed by Angela • Produced by Angela • Concept by Angela • Quality controlled by Angela • Academic chaos managed by Angela</span><small>© 2026 Angela. All rights reserved.</small></footer>
  </main>
</div></div>};createRoot(document.getElementById('root')).render(<App/>);
