create table public.profiles (id uuid primary key references auth.users on delete cascade, username text unique not null, current_streak int default 0, last_study_date date);
create table public.study_sessions (id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,subject text not null check(subject in ('Biology','Physics','Chemistry','Psychology')),hours numeric not null check(hours>0 and hours<=12),topic text not null,report text not null,points int not null,studied_on date default current_date,created_at timestamptz default now());
create or replace function public.new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,username) values(new.id, coalesce(new.raw_user_meta_data->>'username','student-'||left(new.id::text,6))); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.new_user();
alter table profiles enable row level security; alter table study_sessions enable row level security;
create policy "profiles public read" on profiles for select using(true); create policy "profile own update" on profiles for update using(auth.uid()=id);
create policy "sessions own read" on study_sessions for select using(auth.uid()=user_id); create policy "sessions own insert" on study_sessions for insert with check(auth.uid()=user_id);
create view public.leaderboard with (security_invoker=true) as select p.id,p.username,p.current_streak,coalesce(sum(s.hours),0) total_hours,coalesce(sum(s.points),0)::int total_points from profiles p left join study_sessions s on p.id=s.user_id group by p.id,p.username,p.current_streak;
grant select on public.leaderboard to anon,authenticated;
